# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

distMat <- function(nn, dd, ZZ) {
    .Call('LLSM_distMat', PACKAGE = 'LLSM', nn, dd, ZZ)
}

FullLogLik <- function(YY, ZZ, intercept, nn, dd) {
    .Call('LLSM_FullLogLik', PACKAGE = 'LLSM', YY, ZZ, intercept, nn, dd)
}

likelihoodi <- function(ii, dd, nn, Yt, Zt, intercept) {
    .Call('LLSM_likelihoodi', PACKAGE = 'LLSM', ii, dd, nn, Yt, Zt, intercept)
}

varZero <- function(Phi, TT, dd, Zvar) {
    .Call('LLSM_varZero', PACKAGE = 'LLSM', Phi, TT, dd, Zvar)
}

logMVNkern <- function(Z, mu, Sigma) {
    .Call('LLSM_logMVNkern', PACKAGE = 'LLSM', Z, mu, Sigma)
}

logdmvnorm <- function(Z, mu, Sigma, dd) {
    .Call('LLSM_logdmvnorm', PACKAGE = 'LLSM', Z, mu, Sigma, dd)
}

Zllik <- function(ZZ, TT, dd, nn, Phi, ZVar) {
    .Call('LLSM_Zllik', PACKAGE = 'LLSM', ZZ, TT, dd, nn, Phi, ZVar)
}

Zupdate1 <- function(Yt, Zt, ZNext, TT, Intercept, dd, nn, Phi, var, llikOld, acct, tunet) {
    .Call('LLSM_Zupdate1', PACKAGE = 'LLSM', Yt, Zt, ZNext, TT, Intercept, dd, nn, Phi, var, llikOld, acct, tunet)
}

Zupdatet <- function(Yt, Zt, ZNext, ZPrev, TT, Intercept, dd, nn, Phi, var, llikOld, acct, tunet) {
    .Call('LLSM_Zupdatet', PACKAGE = 'LLSM', Yt, Zt, ZNext, ZPrev, TT, Intercept, dd, nn, Phi, var, llikOld, acct, tunet)
}

ZupdateTT <- function(Yt, Zt, ZPrev, TT, Intercept, dd, nn, Phi, var, llikOld, acct, tunet) {
    .Call('LLSM_ZupdateTT', PACKAGE = 'LLSM', Yt, Zt, ZPrev, TT, Intercept, dd, nn, Phi, var, llikOld, acct, tunet)
}

ZupdateLSM <- function(Y, Z, Intercept, dd, nn, var, llikOld, acc, tune) {
    .Call('LLSM_ZupdateLSM', PACKAGE = 'LLSM', Y, Z, Intercept, dd, nn, var, llikOld, acc, tune)
}

